// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

loadEnv({ path: process.env.DOTENV_CONFIG_PATH || ".env" });

const host = process.env.DB_HOST || process.env.PGHOST;
const port = process.env.DB_PORT || process.env.PGPORT || "25060";
const database = process.env.DB_NAME || process.env.PGDATABASE;
const user = process.env.DB_USER || process.env.PGUSER;
const password = process.env.DB_PASSWORD || process.env.PGPASSWORD;
const sslModeRaw = process.env.DB_SSL || process.env.PGSSLMODE;
const sslRequired = sslModeRaw
  ? !["0", "false", "no", "off", "disable", "disabled"].includes(sslModeRaw.toLowerCase())
  : false;

const databaseUrl =
  process.env.DATABASE_URL ||
  (host && database && user && password
    ? `postgresql://${encodeURIComponent(user)}:${encodeURIComponent(password)}@${host}:${port}/${database}${
        sslRequired ? "?sslmode=require" : ""
      }`
    : "postgresql://invalid:invalid@127.0.0.1:1/invalid");

export default defineConfig({
  schema: "schema.prisma",
  migrations: {
    path: "migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
